### ISSUE TITLE
Error loading layout

### ISSUE THREAD

**Issue by sound118** [openanalytics/shinyproxy-dash-demo#2]
I pulled the docker image from the docker hub, and trying to test the dash-demo application. There's error popping up saying "Error loading layout", and I actually checked this link https://support.openanalytics.eu/t/what-is-the-best-way-of-delivering-static-assets-to-the-client-for-custom-apps/363, but the way it's implemented is not working on my machine. While I have no problem hosting R Shiny apps with shinyproxy. Can you help with this issue deploying python dash app with shinyproxy. Thanks!

**Comment by mnazarov** [comment]
I think you would need to give more details - which version of shinyproxy do you use, which app have you tried? If I use the latest version (2.3.0), pull the `openanalytics/shinyproxy-dash-demo` image and use exactly the same specification in application.yml as in readme on this page, the test app works fine. If you trying to use on your own app, make sure you have setting as in https://github.com/openanalytics/shinyproxy-dash-demo/blob/4b4c6290608d47bc11143a97dc97ef44126d505c/app/app.py#L51-55

**Comment by sound118** [comment]
Yes, I am using ShinyProxy 2.3.0 which is the newest version. Actually, I am installing shinyproxy server on AWS EC2 instance and have been hosting a series of R Shiny APPs which can run with no problem. Today I trired to rerun the dash-demo app again hosted on AWS, it surprisingly works well. 
However, when I host my own dash app, it's bit complicated. "Error loading layout" shows up again. My file structure is like this:
---Dashboard
     ---app.py
     ---assets
         ---base.css
         ---custom.css
     ---data
         ---inputdata.csv
     ---utils
         ---DataProcess.py
---Dockerfile

My Dockerfile is like below:

FROM python:3.7

LABEL maintainer "****************"

#RUN apt-get update && apt-get install -y python python-pip

# Dash and dependencies
RUN pip install dash==1.9.1  # The core dash backend
RUN pip install dash-renderer==1.2.4  # The dash front-end
RUN pip install dash-html-components==1.0.2  # HTML components
RUN pip install dash-core-components==1.8.1  # Supercharged components
RUN pip install dash-bootstrap-components==0.8.3 # bootstrap components
RUN pip install dash-table==4.6.1 # dash table 
RUN pip install plotly --upgrade  # Plotly graphing library used in examples

# app dependencies
RUN pip install pandas
RUN pip install numpy
RUN pip install scipy
RUN pip install jieba
RUN pip install openpyxl
RUN pip install xlrd

RUN mkdir app
COPY Dashboard /app

EXPOSE 8050

WORKDIR /app
CMD ["python", "app.py"]

And in my app.py file, I have some directory like below:
os.chdir("/app")
sys.path.append(os.path.abspath("./utils"))
from DataProcess import split_filter_part, data_preprocessing, text_mining

And in my utils file, I have some directory llike below:
data = pd.read_csv('/app/data/data_file.csv')

I suspect if the issue is caused by these directory. Otherwise, I would have no idea about it since it runs pretty well at local host.

Can you please help with it? Thanks a lot！

**Comment by mnazarov** [comment]
do you have the lines referenced above in your app?
```
app.config.suppress_callback_exceptions = True
app.config.update({
    # as the proxy server will remove the prefix
    'routes_pathname_prefix': ''
    # the front-end will prefix this string to the requests
    # that are made to the proxy server
    , 'requests_pathname_prefix': ''
})
```

**Comment by sound118** [comment]
Yes, I do have all these lines added. Just added you as collaborator. Maybe you can help me with the deployment on shinyproxy. Thanks a lot!

**Comment by ghost** [comment]
@mnazarov for the purpose of reproducing the aforementioned error, it is enough to build the docker image using the latest dash libraries, that is, 

```
FROM ubuntu:18.04

LABEL maintainer "Tobias Verbeke <tobias.verbeke@openanalytics.eu>"

RUN apt-get update && apt-get install -y python python-pip

# Dash and dependencies
RUN pip install dash  # The core dash backend
RUN pip install dash-renderer  # The dash front-end
RUN pip install dash-html-components  # HTML components
RUN pip install dash-core-components  # Supercharged components
RUN pip install plotly --upgrade  # Plotly graphing library used in examples

# app dependencies
RUN pip install pandas

RUN mkdir app
COPY app/app.py /app

EXPOSE 8050

WORKDIR /app
CMD ["python", "app.py"]
```

or equivalently generate your python environment using the following list of packages:
```
asn1crypto==0.24.0
click==7.1.1
cryptography==2.1.4
dash==1.11.0
dash-core-components==1.9.1
dash-html-components==1.0.3
dash-renderer==1.4.0
dash-table==4.6.2
enum34==1.1.6
Flask==1.1.2
Flask-Compress==1.4.0
future==0.18.2
idna==2.6
ipaddress==1.0.17
itsdangerous==1.1.0
Jinja2==2.11.1
keyring==10.6.0
keyrings.alt==3.0
MarkupSafe==1.1.1
numpy==1.16.6
pandas==0.24.2
plotly==4.6.0
pycrypto==2.6.1
pygobject==3.26.1
python-dateutil==2.8.1
pytz==2019.3
pyxdg==0.25
retrying==1.3.3
SecretStorage==2.3.1
six==1.14.0
Werkzeug==1.0.1
asn1crypto==0.24.0
click==7.1.1
cryptography==2.1.4
dash==1.11.0
dash-core-components==1.9.1
dash-html-components==1.0.3
dash-renderer==1.4.0
dash-table==4.6.2
enum34==1.1.6
Flask==1.1.2
Flask-Compress==1.4.0
future==0.18.2
idna==2.6
ipaddress==1.0.17
itsdangerous==1.1.0
Jinja2==2.11.1
keyring==10.6.0
keyrings.alt==3.0
MarkupSafe==1.1.1
numpy==1.16.6
pandas==0.24.2
plotly==4.6.0
pycrypto==2.6.1
pygobject==3.26.1
python-dateutil==2.8.1
pytz==2019.3
pyxdg==0.25
retrying==1.3.3
SecretStorage==2.3.1
six==1.14.0
Werkzeug==1.0.1
```

**Comment by sound118** [comment]
> do you have the lines referenced above in your app?
> 
> ```
> app.config.suppress_callback_exceptions = True
> app.config.update({
>     # as the proxy server will remove the prefix
>     'routes_pathname_prefix': ''
>     # the front-end will prefix this string to the requests
>     # that are made to the proxy server
>     , 'requests_pathname_prefix': ''
> })
> ```

You can reproduce the error I encountered exactly as what Daniel mentioned later using the latest dash package.

**Comment by sound118** [comment]
> @mnazarov for the purpose of reproducing the aforementioned error, it is enough to build the docker image using the latest dash libraries, that is,
> 
> ```
> FROM ubuntu:18.04
> 
> LABEL maintainer "Tobias Verbeke <tobias.verbeke@openanalytics.eu>"
> 
> RUN apt-get update && apt-get install -y python python-pip
> 
> # Dash and dependencies
> RUN pip install dash  # The core dash backend
> RUN pip install dash-renderer  # The dash front-end
> RUN pip install dash-html-components  # HTML components
> RUN pip install dash-core-components  # Supercharged components
> RUN pip install plotly --upgrade  # Plotly graphing library used in examples
> 
> # app dependencies
> RUN pip install pandas
> 
> RUN mkdir app
> COPY app/app.py /app
> 
> EXPOSE 8050
> 
> WORKDIR /app
> CMD ["python", "app.py"]
> ```
> 
> or equivalently generate your python environment using the following list of packages:
> 
> ```
> asn1crypto==0.24.0
> click==7.1.1
> cryptography==2.1.4
> dash==1.11.0
> dash-core-components==1.9.1
> dash-html-components==1.0.3
> dash-renderer==1.4.0
> dash-table==4.6.2
> enum34==1.1.6
> Flask==1.1.2
> Flask-Compress==1.4.0
> future==0.18.2
> idna==2.6
> ipaddress==1.0.17
> itsdangerous==1.1.0
> Jinja2==2.11.1
> keyring==10.6.0
> keyrings.alt==3.0
> MarkupSafe==1.1.1
> numpy==1.16.6
> pandas==0.24.2
> plotly==4.6.0
> pycrypto==2.6.1
> pygobject==3.26.1
> python-dateutil==2.8.1
> pytz==2019.3
> pyxdg==0.25
> retrying==1.3.3
> SecretStorage==2.3.1
> six==1.14.0
> Werkzeug==1.0.1
> asn1crypto==0.24.0
> click==7.1.1
> cryptography==2.1.4
> dash==1.11.0
> dash-core-components==1.9.1
> dash-html-components==1.0.3
> dash-renderer==1.4.0
> dash-table==4.6.2
> enum34==1.1.6
> Flask==1.1.2
> Flask-Compress==1.4.0
> future==0.18.2
> idna==2.6
> ipaddress==1.0.17
> itsdangerous==1.1.0
> Jinja2==2.11.1
> keyring==10.6.0
> keyrings.alt==3.0
> MarkupSafe==1.1.1
> numpy==1.16.6
> pandas==0.24.2
> plotly==4.6.0
> pycrypto==2.6.1
> pygobject==3.26.1
> python-dateutil==2.8.1
> pytz==2019.3
> pyxdg==0.25
> retrying==1.3.3
> SecretStorage==2.3.1
> six==1.14.0
> Werkzeug==1.0.1
> ```

Hi Daniel,

Have you found a way to resolve this kind of deployment issue for Python Dash APPs with latest packages on shinyproxy server?

**Comment by ghost** [comment]
@sound118 I have managed to run the app using the following code:

```
app = dash.Dash(__name__, requests_pathname_prefix='/app_direct/dash-demo/')
app.config.suppress_callback_exceptions = True
# app.config.update({
#     # as the proxy server will remove the prefix
#     'routes_pathname_prefix': ''
#
#     # the front-end will prefix this string to the requests
#     # that are made to the proxy server
#     , 'requests_pathname_prefix': ''
# })
```
The name `dash-demo` in the `requests_pathname_prefix` is the app id taken from `application.yml`

**Comment by sound118** [comment]
@dku-xyt Thanks for your hint. This perfectly resolved my issue. Looks like the latest Dash package has some path name prefix changes as opposed to before.

**Comment by sound118** [comment]
> @sound118 I have managed to run the app using the following code:
> 
> ```
> app = dash.Dash(__name__, requests_pathname_prefix='/app_direct/dash-demo/')
> app.config.suppress_callback_exceptions = True
> # app.config.update({
> #     # as the proxy server will remove the prefix
> #     'routes_pathname_prefix': ''
> #
> #     # the front-end will prefix this string to the requests
> #     # that are made to the proxy server
> #     , 'requests_pathname_prefix': ''
> # })
> ```
> 
> The name `dash-demo` in the `requests_pathname_prefix` is the app id taken from `application.yml`

@dku-xyt I am recently developing a python dash app using flask as the embedding server, which can route to a path using render_template to render a html webpage generated within dash. It works well on my local windows machine. However, when I deploy this app with shinyproxy, the dash UI part can appear, but it just cannot route the html webpage. Instead, the browser says 404 NOT FOUND. Do you have any experience deploying dash-flask app with ShinyProxy? Any help will be appreciated!

**Comment by sound118** [comment]
@dku-xyt You can reproduce the issue with the code on my github repo as below
https://github.com/sound118/Scattertext-for-Chinese

**Comment by jfrubioz** [comment]
@dku-xyt can you share the dash & component version that you were able to launch with your solution `app = dash.Dash(__name__, requests_pathname_prefix='/app_direct/dash-demo/')` ? 
I am failing to deploy my app with:
```
app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP], suppress_callback_exceptions=True, prevent_initial_callbacks=True, requests_pathname_prefix='/app_direct/<appname>')
#app.config.update({
#         # remove the default of '/'
#         'routes_pathname_prefix': '',
#         # remove the default of '/'
#         'requests_pathname_prefix': ''
#    })
```

I did try to include `__name__` and/or exclude `external_stylesheets`
I also tried without success to move the request inside the config.update:
```
app.config.update({
         # remove the default of '/'
         'routes_pathname_prefix': '',
         # remove the default of '/'
         'requests_pathname_prefix': '/app_direct/<appname>/'
})
```

The image is build with:
dash==1.14.0
dash-bootstrap-components==0.10.3
dash-core-components==1.10.2
dash-html-components==1.0.3
dash-renderer==1.6.0
dash-table==4.9.0

For reference, none of this components load:

polyfill@7.v1_6_0m1598451932.8.7.min.js	
react@16.v1_6_0m1598451932.13.0.min.js	
react-dom@16.v1_6_0m1598451932.13.0.min.js	
prop-types@15.v1_6_0m1598451932.7.2.min.js	
dash_bootstrap_components.v0_10_3m1598451933.min.js	
bundle.v4_9_0m1598451932.js	
dash_html_components.v1_0_3m1598451932.min.js	
dash_core_components.v1_10_2m1598451932.min.js	
dash_core_components-shared.v1_10_2m1598451932.js	
dash_renderer.v1_6_0m1598451932.min.js	
react-dom@16.v1_6_0m1598451932.13.0.min.js	
prop-types@15.v1_6_0m1598451932.7.2.min.js	
dash_bootstrap_components.v0_10_3m1598451933.min.js	
bundle.v4_9_0m1598451932.js	
dash_html_components.v1_0_3m1598451932.min.js	
dash_core_components.v1_10_2m1598451932.min.js	
dash_core_components-shared.v1_10_2m1598451932.js	
dash_renderer.v1_6_0m1598451932.min.js

**Comment by fbardos** [comment]
@jfrubioz: Not sure if it helps, but this is my working configuration:

In app.py:
```python
from flask import Flask
import dash
import dash_bootstrap_components as dbc
...
server = Flask(__name__)
app = dash.Dash(
    server=server,
    external_stylesheets=[dbc.themes.BOOTSTRAP],
    suppress_callback_exceptions=True,
    prevent_initial_callbacks=True,
    requests_pathname_prefix=os.environ['SHINYPROXY_PUBLIC_PATH'],
)
...
if __name__ == '__main__':
    app.run_server(port=8050)
```
Installed packages:
```bash
Package                   Version
------------------------- -------
...
dash                      1.19.0
dash-bootstrap-components 0.11.3
dash-core-components      1.15.0
dash-html-components      1.1.2
dash-renderer             1.9.0
dash-table                4.11.2
Flask                     1.1.2
Flask-Compress            1.9.0
...
gunicorn                  20.0.4
...
```
Dockerfile:
```Dockerfile
...
CMD [ "gunicorn", "--workers=1", "--threads=1", "-b 0.0.0.0:8050", "--timeout=30", "app:server"]
```
Shinyproxy version: 2.5.0
