### ISSUE TITLE
Upgrade for dash version 2.x

### ISSUE THREAD

**Issue by nsnr61** [openanalytics/shinyproxy-dash-demo#3]
I suspect, that this solution in not applicable to dash versions >= 2.0  .
I have tried my own Dash App, but it is reproducible as well in the given Demo App:
By simply removing "==1.19.0" from the Docker file (which makes the command pip install dash) it defaults to the latest version of dash(currently 2.1) which is sufficient to reproduce the problem. 
Shinyproxy tries to connect to the container and gives out Error "500" and logs show container not responding, while trying to connect 10 times.
Is there an easy way to fix this issue or is there an update planned to make the connection to dash possible again?
Kind regards!

**Comment by euxhenh** [comment]
I solved it by adding the following to the `application.yml` file under `specs`

```
container-env:
    SCRIPT_NAME: "#{proxy.getRuntimeValue('SHINYPROXY_PUBLIC_PATH').replaceFirst('/$','')}"
target-path: "#{proxy.getRuntimeValue('SHINYPROXY_PUBLIC_PATH')}"
```

Make sure your `routes_pathname_prefix` and `requests_pathname_prefix` still point to the `SHINYPROXY_PUBLIC_PATH` environment variable.

Source: [https://github.com/openanalytics/shinyproxy-flask-demo](https://github.com/openanalytics/shinyproxy-flask-demo)

Can confirm it works with dash 2.3.

**Comment by nsnr61** [comment]
@euxhenh Thank you very much this works for me on all versions of dash >= 2.0.0 !
CAVE: For anyone trying this with this repository, do not forget to get a minimal working example, you have to move the "read-only" options `routes_pathname_prefix` and `requests_pathname_prefix` to the Dash constructor:  
`dash.Dash(routes_pathname_prefix=os.environ['SHINYPROXY_PUBLIC_PATH'],   requests_pathname_prefix=os.environ['SHINYPROXY_PUBLIC_PATH'])`

Once again thank you for solving my problem, i'm closing this issue.
